### PR TITLE
Add new schema for NTS

### PR DESCRIPTION
**Pull request by David-Henandez-nrcan**
* Add new schemas and tests for 'Locate' and 'NTS'
* Refactoring of schema-service procedure improve performance
* Code cleanup

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/54)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/54)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @David-Henandez-nrcan)

___
*[`cloud-formation/python/geolocator-lambda.py` line 62 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/54#-NPJhTna-1CvyUyzdrub:-NPJhTna-1CvyUyzdruc:b9k8ljd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1b673e05a9b698dcd36e9f8c5561251b182231e8/cloud-formation/python/geolocator-lambda.py#L62)):*
> ```Python
>                                    service_load)
>         t4 = time.time()
>         print(f"main-Get schema: {((t1-t0)*1000):.3f}")
> ```

Can we remove timer ad debug from PR. We can create a new branch on the upstream with this but not in the branch to go to prod
___
*[`cloud-formation/python/model_manager.py` line 96 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/54#-NPJhj7_16qvhbhJkbj5:-NPJhj7_16qvhbhJkbj6:bpp6p6n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1b673e05a9b698dcd36e9f8c5561251b182231e8/cloud-formation/python/model_manager.py#L96)):*
> ```Python
>         return function_null
>     if not lookup:
>         return get_from_schema        
> ```

Remove trailing blankspace
___
*[`cloud-formation/python/model_manager.py` line 338 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/54#-NPJhvxFD__MHMNIdNpY:-NPJhvxFD__MHMNIdNpZ:bd0liqx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1b673e05a9b698dcd36e9f8c5561251b182231e8/cloud-formation/python/model_manager.py#L338)):*
> ```Python
>             # Add the item to the list for the next process
>             list_to_process.append((schema_items, schema_required, item))
>         print(f"adapt to model-start: {(tt101*1000):.3f}")
> ```

Reference to test, please remove

**Review by David-Henandez-nrcan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/54)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`cloud-formation/python/geolocator-lambda.py` line 62 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/54#-NPJhTna-1CvyUyzdrub:-NPJq2SH7aD97Ue1m-HT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1b673e05a9b698dcd36e9f8c5561251b182231e8/cloud-formation/python/geolocator-lambda.py#L62)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we remove timer ad debug from PR. We can create a new branch on the upstream with this but not in the branch to go to prod
</blockquote></details>

Done.
___
*[`cloud-formation/python/model_manager.py` line 96 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/54#-NPJhj7_16qvhbhJkbj5:-NPJq3qmCKz5gYj6-dP1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1b673e05a9b698dcd36e9f8c5561251b182231e8/cloud-formation/python/model_manager.py#L96)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing blankspace
</blockquote></details>

Done.
___
*[`cloud-formation/python/model_manager.py` line 338 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/54#-NPJhvxFD__MHMNIdNpY:-NPJq6vsBuR0k8eMttEg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1b673e05a9b698dcd36e9f8c5561251b182231e8/cloud-formation/python/model_manager.py#L338)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Reference to test, please remove
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/54)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @David-Henandez-nrcan)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @David-Henandez-nrcan)

**Pull request merged**
