### PR TITLE
Updates for missing table codes #75

### PR DESCRIPTION
**Pull request by JeffreyAshtonNRCan**
The lookup tables will now update from the service urls, when codes are missing.  New CSV files also generated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76)* status: 5 of 6 files reviewed, 13 unresolved discussions (waiting on @DamonU2 and @JeffreyAshtonNRCan)

___
*[`backend/api-lambda/model_manager.py` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswNyMDmoDvgqTuUQz:-NjswNyMDmoDvgqTuUR-:bcs0mtf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L51)):*
> ```Python
>     if code in tables.get(table_name):
>        return tables.get(table_name).get(code).get(lang)
>     
> ```

Remove blank space
___
*[`backend/api-lambda/model_manager.py` line 57 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswUDZ9fyli7HjrXzZ:-NjswUDZ9fyli7HjrXz_:btq66kg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L57)):*
> ```Python
>     term = {'en' : term_en, 'fr' : term_fr}
>     
>     #add missing code to table
> ```

Space after #
___
*[`backend/api-lambda/model_manager.py` line 58 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswZa_CKnQRBkSRnGz:-NjswZa_CKnQRBkSRnH-:b-vt7ogs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L58)):*
> ```Python
>     
>     #add missing code to table
>     if term_en != 'undefined' and term_fr != 'undefined':
> ```

Should we have OR instead of AND?
___
*[`backend/api-lambda/model_manager.py` line 66 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswecQBZJZrdbhMH68:-NjswecQBZJZrdbhMH69:bcs0mtf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L66)):*
> ```Python
> def get_table_code(tables, table_name, code, lang):
>     """
>     get missing code definition from service url  
> ```

Remove blank space
___
*[`backend/api-lambda/model_manager.py` line 67 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswXKeAyVMsg3-gkYZ:-NjswXKeAyVMsg3-gkY_:bcs0mtf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L67)):*
> ```Python
>     """
>     get missing code definition from service url  
>     
> ```

Remove blank space
___
*[`backend/api-lambda/model_manager.py` line 76 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njswkm802K5DEokJceJ:-Njswkm802K5DEokJceK:bcs0mtf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L76)):*
> ```Python
>         The term or description of the missing code for the lang 
>     """
>     
> ```

Remove blank space
___
*[`backend/api-lambda/model_manager.py` line 77 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njswnah8-Zq6HBYiU0d:-Njswnah8-Zq6HBYiU0e:bcs0mtf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L77)):*
> ```Python
>     """
>     
>     if lang not in service_tables[table_name]:   
> ```

Remove blank space
___
*[`backend/api-lambda/model_manager.py` line 88 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswmeE4hUGHTrPhx_9:-NjswmeE4hUGHTrPhx_A:bcs0mtf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L88)):*
> ```Python
>                 print('Error=', error, ' url:', table_url)
>                 return 'undefined'
>         else: 
> ```

Remove blank space
___
*[`backend/api-lambda/s3_manager.py` line 76 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswslM6Enrk2CTaDSO:-NjswslN73nMGFmbfZLg:bcs0mtf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/s3_manager.py#L76)):*
> ```Python
> def write_table(bucket_name, table_name, tables):
>     """
>     write table content to csv file in bucket's tables path 
> ```

Remove blank space
___
*[`backend/api-lambda/s3_manager.py` line 82 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswtUL3UwjRXWhM8ZK:-NjswtUM0efTfhq_IBoQ:bcs0mtf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/s3_manager.py#L82)):*
> ```Python
>       table_name: generic or province 
>       tables: tables to create csv from
>     Return:  
> ```

Remove blank space
___
*[`backend/api-lambda/s3_manager.py` line 88 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswuEs4398hoiaKZir:-NjswuEs4398hoiaKZis:bcs0mtf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/s3_manager.py#L88)):*
> ```Python
>     table = tables.get(table_name)
>     csv_columns = ['code','en','fr']
>     
> ```

Remove blank space
___
*[`backend/api-lambda/s3_manager.py` line 104 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswwPM7fWLz3jV83uA:-NjswwPM7fWLz3jV83uB:bcs0mtf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/s3_manager.py#L104)):*
> ```Python
>         print("content_object write error to S3 bucket", type(error).__name__)
>         print('error=', error)
>         
> ```

Remove blank space
___
*[`backend/api-lambda/s3_manager.py` line 106 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njswx3X1CjQ_DiNbkPX:-Njswx3X1CjQ_DiNbkPY:bcs0mtf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/s3_manager.py#L106)):*
> ```Python
>         
>     return
>     
> ```

Remove blank space

**Review by DamonU2 — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76)* status: all files reviewed, 16 unresolved discussions (waiting on @JeffreyAshtonNRCan)

___
*[`backend/api-lambda/model_manager.py` line 59 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njsxx27EcUw3TU0O6ys:-Njsxx27EcUw3TU0O6yt:b-npsish) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L59)):*
> ```Python
>     #add missing code to table
>     if term_en != 'undefined' and term_fr != 'undefined':
>         tables[table_name][code] = term  
> ```

More blank spaces
___
*[`backend/api-lambda/model_manager.py` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njsy0uP55RP28fNcSSQ:-Njsy0uP55RP28fNcSSR:b-1osywe) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L78)):*
> ```Python
>     
>     if lang not in service_tables[table_name]:   
>         if 'tableurl' in tables:  
> ```

And again
___
*[`backend/api-lambda/s3_manager.py` line 89 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njsy9Tx9yiU14qYfxUS:-Njsy9Tx9yiU14qYfxUT:bqujbyh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/s3_manager.py#L89)):*
> ```Python
>     csv_columns = ['code','en','fr']
>     
>     csv_string = io.StringIO()  # create csv to string  
> ```

Here too

**Review by JeffreyAshtonNRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76)* status: 4 of 6 files reviewed, 16 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`backend/api-lambda/model_manager.py` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswNyMDmoDvgqTuUQz:-NjxUNM401BxSFGj4ZPm:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L51)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank space
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 57 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswUDZ9fyli7HjrXzZ:-NjxUOrZCS2wGFQ9jLJr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L57)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after #
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 58 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswZa_CKnQRBkSRnGz:-NjwQJMWBZRhZKJxnsrW:b-4tvm7i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L58)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we have OR instead of AND?
</blockquote></details>

OR will update the  code in the csv file, with potentially one language undefined.  AND will try again on the next invocation to get both languages, before updating the csv file.   
___
*[`backend/api-lambda/model_manager.py` line 59 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njsxx27EcUw3TU0O6ys:-NjxUQB16V9fS7vYx3ub:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L59)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

More blank spaces
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 66 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswecQBZJZrdbhMH68:-NjxUQoQCy5SM1sI-juB:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L66)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank space
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 67 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswXKeAyVMsg3-gkYZ:-NjxUROR8fRGyWOYXVt3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L67)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank space
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 76 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njswkm802K5DEokJceJ:-NjxURwnEhcZkIqXkWFc:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L76)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank space
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 77 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njswnah8-Zq6HBYiU0d:-NjxUSSn6Im_ct6O5LEZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L77)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank space
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njsy0uP55RP28fNcSSQ:-NjxUT530Ae8gJ4KhTRw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L78)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

And again
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 88 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswmeE4hUGHTrPhx_9:-NjxUTm29SHG_pZRaMat:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L88)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank space
</blockquote></details>

Done.
___
*[`backend/api-lambda/s3_manager.py` line 82 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswtUL3UwjRXWhM8ZK:-NjxWeLX-cSWbbcfRMtR:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/s3_manager.py#L82)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank space
</blockquote></details>

Done.
___
*[`backend/api-lambda/s3_manager.py` line 88 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswuEs4398hoiaKZir:-NjxWfyQ8ryZavagCkB1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/s3_manager.py#L88)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank space
</blockquote></details>

Done.
___
*[`backend/api-lambda/s3_manager.py` line 89 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njsy9Tx9yiU14qYfxUS:-NjxWh629qpw9ago3r68:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/s3_manager.py#L89)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Here too
</blockquote></details>

Done.
___
*[`backend/api-lambda/s3_manager.py` line 104 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswwPM7fWLz3jV83uA:-NjxWpPb6Qq0enyyd3mc:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/s3_manager.py#L104)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank space
</blockquote></details>

Done.
___
*[`backend/api-lambda/s3_manager.py` line 106 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njswx3X1CjQ_DiNbkPX:-NjxWpju2JawbEIT7Ft9:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/s3_manager.py#L106)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank space
</blockquote></details>

Done.

**Review by JeffreyAshtonNRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76)* status: 4 of 6 files reviewed, 16 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`backend/api-lambda/s3_manager.py` line 76 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswslM6Enrk2CTaDSO:-NjxfH8G5e6wOUII54F9:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/s3_manager.py#L76)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank space
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76)* status: 4 of 6 files reviewed, 13 unresolved discussions (waiting on @DamonU2 and @JeffreyAshtonNRCan)

___
*[`backend/api-lambda/model_manager.py` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjswNyMDmoDvgqTuUQz:-NjxtriLEF9PwKgZh3yq:b-8dahjt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e1fa6ecd9291e646863c041634d17e1f74eb3cb8/backend/api-lambda/model_manager.py#L51)):*
<details><summary><i>Previously, JeffreyAshtonNRCan wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still there
___
*[`backend/api-lambda/model_manager.py` line 7 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-Njxto2U8v2kGZXJjdoy:-Njxto2U8v2kGZXJjdoz:bnle2gl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L7)):*
> ```Python
> from constants import *
> 
> # tables from json service url 
> ```

Blank space
___
*[`backend/api-lambda/model_manager.py` line 8 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjxtpXm6lEZUyuD8TS7:-NjxtpXm6lEZUyuD8TS8:bnle2gl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L8)):*
> ```Python
> 
> # tables from json service url 
> service_tables = {'generic': {}, 'province': {}} 
> ```

Blank space
___
*[`backend/api-lambda/model_manager.py` line 64 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjxtuZSBLz6DHn5x-zR:-NjxtuZSBLz6DHn5x-zS:b-8dahjt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L64)):*
> ```Python
> def get_table_code(tables, table_name, code, lang):
>     """
>     get missing code definition from service url  
> ```

Still there
___
*[`backend/api-lambda/model_manager.py` line 73 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjxtwPuD6oYrMDoshHK:-NjxtwPuD6oYrMDoshHL:b-8dahjt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L73)):*
> ```Python
>         The term or description of the missing code for the lang 
>     """
>     if lang not in service_tables[table_name]:   
> ```

Still there
___
*[`backend/api-lambda/s3_manager.py` line 76 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/76#-NjxthjDAZWPrU1X8caA:-NjxthjDAZWPrU1X8caB:b-8dahjt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L76)):*
> ```Python
> def write_table(bucket_name, table_name, tables):
>     """
>     write table content to csv file in bucket's tables path 
> ```

Still there

**Pull request closed without merging**
