### PR TITLE
Add multiprocessing to improve the response time

### PR DESCRIPTION
**Pull request by David-Henandez-nrcan**
- Add the module lambda_multiprocessing.py
- Replace several functions inside module module model_manager.py to process in parallel each field from the items obtained from the REST request in order to speed up the processing time.
- Modify the geolocator-lambda.py main module to use those new methods.
- Redact in readme.md the documentation related to the processing time.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @David-Henandez-nrcan)

___
*[`schemas/README.md` line 98 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-NNx3bk9EtLF0XFMsQAe:-NNx3bk9EtLF0XFMsQAf:b7tiujx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/9e5d160f6d8c1a73847606748525d5b8b2118064/schemas/README.md#L98)):*
> ```Markdown
> ```
> 
> ### Response time
> ```

Can you add some statistic about how long a query to the service directly versus from our API in millisecond. For both API and one where we combine the 2 services in list of keys. Do not take into account the singleton creation.

**Comment by David-Henandez-nrcan** [comment]
A comparative table for some query results.
 - Going from very specific to 
 - Very generic with 100+ results.

comparative table for query response

**Review by David-Henandez-nrcan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview-api-geolocator/51)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`schemas/README.md` line 98 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview-api-geolocator/51#-NNx3bk9EtLF0XFMsQAe:-NOAAmMC7FTAIVxb5Dle:bmqp43q) ([raw file](https://github.com/canadian-geospatial-platform/geoview-api-geolocator/blob/9e5d160f6d8c1a73847606748525d5b8b2118064/schemas/README.md#L98)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add some statistic about how long a query to the service directly versus from our API in millisecond. For both API and one where we combine the 2 services in list of keys. Do not take into account the singleton creation.
</blockquote></details>

I added a table with a few examples with payload varying in size. The number of items returned by the request is the main factor for the delay in the processing time.

**Review by David-Henandez-nrcan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51)* status: 2 of 13 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`schemas/README.md` line 98 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-NNx3bk9EtLF0XFMsQAe:-NOApXBJ9toiS_CEyH8R:b40ph7n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/9e5d160f6d8c1a73847606748525d5b8b2118064/schemas/README.md#L98)):*
> oad varying in size. The number of items returned by the request is the main factor for the processing time

**Review by David-Henandez-nrcan — COMMENTED** [review]
Depending on how specific the query is, it might return a different amount of items in the payload.
Due to the proportionally larger number of transformations required, this affects the response latency of the API.

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-:-NOAuDgI4FdDeallpBOo:b53ws7e)* status: 2 of 13 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 8 of 8 files at r2, 7 of 7 files at r3, 9 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51)* status: 17 of 18 files reviewed, 4 unresolved discussions (waiting on @David-Henandez-nrcan)

___
*[`cloud-formation/python/geolocator.py` line 61 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-NOKit3I4E6xp6F4jVFA:-NOKit3J860gg5f7LxA1:b7zf2ir) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/4d402dcce34bdff4524e6cde84a28842199e28ef/cloud-formation/python/geolocator.py#L61)):*
> ```Python
>         """
>         Identifies the table and record to get the value from
>         
> ```

Trailing white spaces
___
*[`cloud-formation/python/geolocator.py` line 67 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-NOKjIFt9Ziyp36oY0dp:-NOKjIFu6GL7kJuVUacR:b7zf2ir) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/4d402dcce34bdff4524e6cde84a28842199e28ef/cloud-formation/python/geolocator.py#L67)):*
> ```Python
>                 - The seconde one is the name of the field in the schema to
>                   look into in the table
>         
> ```

Trailing white spaces
___
*[`cloud-formation/python/model_manager.py` line 213 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-NNx4Dw96hK0HN_4qnwC:-NNx4Dw96hK0HN_4qnwD:b-21y050) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/9e5d160f6d8c1a73847606748525d5b8b2118064/cloud-formation/python/model_manager.py#L213)):*
> ```Python
>         return {key : list_for_field}
>     else:
>         print("Dont know!")
> ```

Can you put a more meaningful message
___
*[`cloud-formation/python/url_methods.py` line 48 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-NOKjkLwCA7ozuPpLfCW:-NOKjkLwCA7ozuPpLfCX:bqz48au) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/4d402dcce34bdff4524e6cde84a28842199e28ef/cloud-formation/python/url_methods.py#L48)):*
> ```Python
>     """
>     print("from url")
>     print(schema)
> ```

Is it for testing or it will print all the time?
___
*[`schemas/README.md` line 98 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-NNx3bk9EtLF0XFMsQAe:-NOKk4_534I6A_pbidBX:bxqcoz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/9e5d160f6d8c1a73847606748525d5b8b2118064/schemas/README.md#L98)):*
<details><summary><i>Previously, David-Henandez-nrcan (David Hernandez) wrote…</i></summary><blockquote>

> oad varying in size. The number of items returned by the request is the main factor for the processing time
</blockquote></details>

Does the urls for testing up to date? Can you add the url for speed testing you show me yesterday.

**Review by David-Henandez-nrcan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51)* status: 15 of 18 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[`cloud-formation/python/geolocator.py` line 61 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-NOKit3I4E6xp6F4jVFA:-NOKmklX0Gex3RfmLrtK:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/4d402dcce34bdff4524e6cde84a28842199e28ef/cloud-formation/python/geolocator.py#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Done.
___
*[`cloud-formation/python/geolocator.py` line 67 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-NOKjIFt9Ziyp36oY0dp:-NOKmm0t3AF97aeUbEgV:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/4d402dcce34bdff4524e6cde84a28842199e28ef/cloud-formation/python/geolocator.py#L67)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Done.

**Review by David-Henandez-nrcan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51)* status: 15 of 18 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[`cloud-formation/python/model_manager.py` line 213 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-NNx4Dw96hK0HN_4qnwC:-NOKpyp296PcQa0Uppev:b-fjofu0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/9e5d160f6d8c1a73847606748525d5b8b2118064/cloud-formation/python/model_manager.py#L213)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put a more meaningful message
</blockquote></details>

changed to:
ERR_UNEXPECTED_SCHEMA_TYPE = "An unexpected type of schema for this field"
___
*[`cloud-formation/python/url_methods.py` line 48 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-NOKjkLwCA7ozuPpLfCW:-NOKqSco6SB1r9ZbDkof:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/4d402dcce34bdff4524e6cde84a28842199e28ef/cloud-formation/python/url_methods.py#L48)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it for testing or it will print all the time?
</blockquote></details>

Done.
___
*[`schemas/README.md` line 98 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51#-NNx3bk9EtLF0XFMsQAe:-NOKxEu9EdUv82BRILrp:bxudmxa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/9e5d160f6d8c1a73847606748525d5b8b2118064/schemas/README.md#L98)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Does the urls for testing up to date? Can you add the url for speed testing you show me yesterday.
</blockquote></details>

I added to readme.md

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/51)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @David-Henandez-nrcan)

**Pull request merged**
