### PR TITLE
75 missing table codes

### PR DESCRIPTION
**Pull request by JeffreyAshtonNRCan**
The lookup tables will now update from the service urls, when codes are missing.  New CSV files also generated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77)* status: 2 of 6 files reviewed, 15 unresolved discussions (waiting on @JeffreyAshtonNRCan)

___
*[`backend/api-lambda/geolocator.py` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1SpSz6CoFeY4rlg38:-Nk1SpSz6CoFeY4rlg39:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/geolocator.py#L79)):*
> ```Python
>         Write the tables to S3 service
> 
>         Return:  
> ```

Blank
___
*[`backend/api-lambda/index.py` line 69 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1TNnZDXa3uX-dMQt0:-Nk1TNnZDXa3uX-dMQt1:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/index.py#L69)):*
> ```Python
>         loads.extend(items)
> 
>     # write csv files if table updated 
> ```

Blank
___
*[`backend/api-lambda/model_manager.py` line 8 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1StloECGD14yNgxOQ:-Nk1StloECGD14yNgxOR:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L8)):*
> ```Python
> 
> # tables from json service url 
> service_tables = {'generic': {}, 'province': {}} 
> ```

Blank
___
*[`backend/api-lambda/model_manager.py` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1SvXKCI9Rz2hYgwxj:-Nk1SvXKCI9Rz2hYgwxk:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L51)):*
> ```Python
>     if code in tables.get(table_name):
>        return tables.get(table_name).get(code).get(lang)
>     
> ```

Blank
___
*[`backend/api-lambda/model_manager.py` line 58 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1SwnDEXY8P0thixVX:-Nk1SwnDEXY8P0thixVY:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L58)):*
> ```Python
>     # add missing code to table
>     if term_en != 'undefined' and term_fr != 'undefined':
>         tables[table_name][code] = term  
> ```

Blank
___
*[`backend/api-lambda/model_manager.py` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1SyHt-oxRjqk-P-kv:-Nk1SyHt-oxRjqk-P-kw:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L64)):*
> ```Python
> def get_table_code(tables, table_name, code, lang):
>     """
>     get missing code definition from service url  
> ```

Blank
___
*[`backend/api-lambda/model_manager.py` line 73 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T-HU5YaCDoFFcnNo:-Nk1T-HU5YaCDoFFcnNp:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L73)):*
> ```Python
>         The term or description of the missing code for the lang 
>     """
>     if lang not in service_tables[table_name]:   
> ```

Blank
___
*[`backend/api-lambda/model_manager.py` line 74 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T1GHAR0B66v-YVXM:-Nk1T1GHAR0B66v-YVXN:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L74)):*
> ```Python
>     """
>     if lang not in service_tables[table_name]:   
>         if 'tableurl' in tables:  
> ```

Blank
___
*[`backend/api-lambda/s3_manager.py` line 76 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T5O82_kGTkzgTS1L:-Nk1T5O82_kGTkzgTS1M:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L76)):*
> ```Python
> def write_table(bucket_name, table_name, tables):
>     """
>     write table content to csv file in bucket's tables path 
> ```

Blank
___
*[`backend/api-lambda/s3_manager.py` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T64W2eRX-gfm3pcR:-Nk1T64W2eRX-gfm3pcS:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L79)):*
> ```Python
>     Param:
>       bucket_name: The name of the bucket to write to
>       table_name: generic or province 
> ```

Blank
___
*[`backend/api-lambda/s3_manager.py` line 81 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T6fo9JWVbfoMoSWr:-Nk1T6fo9JWVbfoMoSWs:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L81)):*
> ```Python
>       table_name: generic or province 
>       tables: tables to create csv from
>     Return:  
> ```

Blank
___
*[`backend/api-lambda/s3_manager.py` line 87 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T7M2499fQtNY4bpD:-Nk1T7M2499fQtNY4bpE:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L87)):*
> ```Python
>     table = tables.get(table_name)
>     csv_columns = ['code','en','fr']
>     csv_string = io.StringIO()  # create csv to string  
> ```

Blank
___
*[`backend/api-lambda/s3_manager.py` line 90 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T88NBhCGK4N65gQl:-Nk1T88NBhCGK4N65gQm:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L90)):*
> ```Python
>     writer = csv.DictWriter(csv_string, fieldnames=csv_columns)
>     writer.writeheader()
>     for num,val in sorted(table.items(), key=lambda num: int(num[0])):  # sort by code as integer 
> ```

Blank
___
*[`backend/api-lambda/s3_manager.py` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1TA7i5P3D9C3TWaHW:-Nk1TA7i5P3D9C3TWaHX:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L103)):*
> ```Python
>         print('error=', error)
>     return
>     
> ```

Blank
___
*[`backend/geolocator-bucket-content/tables/README.md` line 8 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1TBmR57fHjNlp-RxG:-Nk1TBmR57fHjNlp-RxH:b-8ac71t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/geolocator-bucket-content/tables/README.md#L8)):*
> ```Markdown
> The generic.csv and province.csv files are loaded into tables, to reduce API calls to the geonames service.
> 
> The geonames urls in tableurl.csv are used when tables need to be updated. 
> ```

Blank

**Review by JeffreyAshtonNRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77)* status: 2 of 6 files reviewed, 15 unresolved discussions (waiting on @jolevesq)

___
*[`backend/api-lambda/geolocator.py` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1SpSz6CoFeY4rlg38:-Nk1YSZIC3dXoBzo3Rie:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/geolocator.py#L79)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

Done.
___
*[`backend/api-lambda/index.py` line 69 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1TNnZDXa3uX-dMQt0:-Nk1ZBqv72P5nZMWsdQG:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/index.py#L69)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 8 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1StloECGD14yNgxOQ:-Nk1ZSH5CxfyxX0y9GjS:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L8)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1SvXKCI9Rz2hYgwxj:-Nk1ZcjA0BKCb_fXFWD5:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L51)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 58 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1SwnDEXY8P0thixVX:-Nk1_k8MDG46uQJV9fk3:bnqsamk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L58)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

Usually want a blank line before function definitions (def)
___
*[`backend/api-lambda/model_manager.py` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1SyHt-oxRjqk-P-kv:-Nk1a3s29am2yCB9nIuH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L64)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 73 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T-HU5YaCDoFFcnNo:-Nk1aT1Q-ytKjIVdOB1A:br65m2d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L73)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

This was removed, the blank line is not in my local or my fork.
___
*[`backend/api-lambda/model_manager.py` line 74 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T1GHAR0B66v-YVXM:-Nk1afbRA-_T6jnOt6T6:br65m2d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/model_manager.py#L74)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

This was removed, the blank line is not in my local or my fork.
___
*[`backend/api-lambda/s3_manager.py` line 76 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T5O82_kGTkzgTS1L:-Nk1bBVQA2SusRaJdfDJ:bz8v6b9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L76)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

This was removed, the blank line is not in my local or my fork.
___
*[`backend/api-lambda/s3_manager.py` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T64W2eRX-gfm3pcR:-Nk1bRYKEriV9wKqYLKr:bz8v6b9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L79)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

This was removed, the blank line is not in my local or my fork.
___
*[`backend/api-lambda/s3_manager.py` line 81 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T6fo9JWVbfoMoSWr:-Nk1bXfVEHCw72E0BVn1:bz8v6b9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L81)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

This was removed, the blank line is not in my local or my fork.
___
*[`backend/api-lambda/s3_manager.py` line 87 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T7M2499fQtNY4bpD:-Nk1bbO9A74k7da23bq4:bz8v6b9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L87)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

This was removed, the blank line is not in my local or my fork.
___
*[`backend/api-lambda/s3_manager.py` line 90 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1T88NBhCGK4N65gQl:-Nk1bkCp4FpMf5XnakEI:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L90)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

Done.
___
*[`backend/api-lambda/s3_manager.py` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1TA7i5P3D9C3TWaHW:-Nk1boIC7gGtjD-iS7gn:b39gbwp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/api-lambda/s3_manager.py#L103)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

Usually want a blank line before function definition
___
*[`backend/geolocator-bucket-content/tables/README.md` line 8 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk1TBmR57fHjNlp-RxG:-Nk1cS6Q3Egs-Ci-KasD:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cf88505f5e4cb268a9c3ed4c2de6596e4700b134/backend/geolocator-bucket-content/tables/README.md#L8)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @JeffreyAshtonNRCan)

___
*[`backend/api-lambda/model_manager.py` line 7 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk25721CLUsYh5vDQXl:-Nk25721CLUsYh5vDQXm:bl3zkm6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1ca63c7c1ecc41cffde1ae5a9b2464576187589e/backend/api-lambda/model_manager.py#L7)):*
> ```Python
> from constants import *
> 
> # tables from json service url 
> ```

Blank spaces
___
*[`backend/api-lambda/model_manager.py` line 51 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk251gO1wzGBxWavAtr:-Nk251gO1wzGBxWavAts:bl3zkm6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1ca63c7c1ecc41cffde1ae5a9b2464576187589e/backend/api-lambda/model_manager.py#L51)):*
> ```Python
>     if code in tables.get(table_name):
>        return tables.get(table_name).get(code).get(lang)
>     
> ```

Blank spaces
___
*[`backend/api-lambda/model_manager.py` line 56 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk254xt8YFjsnhI7eMp:-Nk254xt8YFjsnhI7eMq:bl3zkm6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1ca63c7c1ecc41cffde1ae5a9b2464576187589e/backend/api-lambda/model_manager.py#L56)):*
> ```Python
>     term_fr = get_table_code(tables, table_name, code, 'fr')
>     term = {'en' : term_en, 'fr' : term_fr}
>     
> ```

Blank spaces
___
*[`backend/api-lambda/model_manager.py` line 89 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk25DQv4yU8qa_im_Su:-Nk25DQv4yU8qa_im_Sv:bl3zkm6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1ca63c7c1ecc41cffde1ae5a9b2464576187589e/backend/api-lambda/model_manager.py#L89)):*
> ```Python
>             print('tableurl.csv missing from S3 bucket')
>             return 'undefined'
>         
> ```

Blank spaces
___
*[`backend/api-lambda/model_manager.py` line 98 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk25Ezi1QGE4T1Z546h:-Nk25Ezi1QGE4T1Z546i:bl3zkm6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1ca63c7c1ecc41cffde1ae5a9b2464576187589e/backend/api-lambda/model_manager.py#L98)):*
> ```Python
>                 else:
>                     return definition.get('term')
>                 
> ```

Blank spaces

**Review by JeffreyAshtonNRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @jolevesq)

___
*[`backend/api-lambda/model_manager.py` line 7 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk25721CLUsYh5vDQXl:-Nk28UQ59UNS9DWdEKTg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1ca63c7c1ecc41cffde1ae5a9b2464576187589e/backend/api-lambda/model_manager.py#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank spaces
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 51 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk251gO1wzGBxWavAtr:-Nk28ThD2sewuGexHDam:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1ca63c7c1ecc41cffde1ae5a9b2464576187589e/backend/api-lambda/model_manager.py#L51)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank spaces
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 56 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk254xt8YFjsnhI7eMp:-Nk28T6E2JlEZaG14y52:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1ca63c7c1ecc41cffde1ae5a9b2464576187589e/backend/api-lambda/model_manager.py#L56)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank spaces
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 89 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk25DQv4yU8qa_im_Su:-Nk28SMC2Jsy6_Rbx7hg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1ca63c7c1ecc41cffde1ae5a9b2464576187589e/backend/api-lambda/model_manager.py#L89)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank spaces
</blockquote></details>

Done.
___
*[`backend/api-lambda/model_manager.py` line 98 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk25Ezi1QGE4T1Z546h:-Nk28Rns3HvuQEOtjdRa:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1ca63c7c1ecc41cffde1ae5a9b2464576187589e/backend/api-lambda/model_manager.py#L98)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank spaces
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77)* status: all files reviewed, 1 unresolved discussion (waiting on @JeffreyAshtonNRCan)

___
*[`backend/api-lambda/index.py` line 68 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77#-Nk28tizBH1NaAe4X8aq:-Nk28tizBH1NaAe4X8ar:bl3zkm6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/1ca63c7c1ecc41cffde1ae5a9b2464576187589e/backend/api-lambda/index.py#L68)):*
> ```Python
>                                    service_load)
>         loads.extend(items)
>         
> ```

Blank spaces

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/77)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JeffreyAshtonNRCan)

**Pull request merged**
