### PR TITLE
82 location names

### PR DESCRIPTION
**Pull request by JeffreyAshtonNRCan**
Issue #82 Data normalization - location names.  Location names and tag types are now returned with similar formats for all keys.  Duplicates removed.  IW (International Waters) and UF (Undersea Feature) added for province codes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @JeffreyAshtonNRCan)

___
*[`backend/geolocator-bucket-content/tables/category.csv` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83#-Nniei3R1YTqG73kteDC:-Nniei3S-VqyLplWL7tv:b-9m3spk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/c0578a210ed27122c47c3a89d9ce67a674c4b468/backend/geolocator-bucket-content/tables/category.csv#L2)):*
> ```CSV
> code,en,fr
> aeroway,Aeroway,Aéroway
> ```

See my email for French translation
___
*[`schemas/tables/category.csv` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83#-Nnif6N_17TG-gUaMWn7:-Nnif6N_17TG-gUaMWn8:b-p9eikg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/c0578a210ed27122c47c3a89d9ce67a674c4b468/schemas/tables/category.csv#L1)):*
> ```CSV
> code,en,fr
> ```

This info is in another file... is this a duplicate, do we need both?

**Review by JeffreyAshtonNRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`backend/geolocator-bucket-content/tables/category.csv` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83#-Nniei3R1YTqG73kteDC:-NnjQmOl9QSBirLGRSA4:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/c0578a210ed27122c47c3a89d9ce67a674c4b468/backend/geolocator-bucket-content/tables/category.csv#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

See my email for French translation
</blockquote></details>

Done.
___
*[`schemas/tables/category.csv` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83#-Nnif6N_17TG-gUaMWn7:-NnjQzuN36OaNeWsZoEu:bswm8el) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/c0578a210ed27122c47c3a89d9ce67a674c4b468/schemas/tables/category.csv#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This info is in another file... is this a duplicate, do we need both?
</blockquote></details>

The province table is for Geonames and can be automatically updated.  The component table is for locate and is manually created.  We can keep both for now.  Will add a note to Readme.

**Comment by JeffreyAshtonNRCan** [comment]
French translations added.  Schema files added.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JeffreyAshtonNRCan)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83)* status: all files reviewed, 1 unresolved discussion (waiting on @JeffreyAshtonNRCan)

___
*[`schemas/tables/category.csv` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83#-NnjbvcD2xV4yykiR1rb:-NnjbvcE6RfKMqxwDE9J:bsv9w0s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e9366474fef14c7ed9c5e2fd341152dd57618b3f/schemas/tables/category.csv#L2)):*
> ```CSV
> code,en,fr
> aeroway,Aeroway,Aéroway
> ```


Use same translation here as the table in bucket-content folder... This is why having twice same content can introduce errors hard to debug.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83)* status: all files reviewed, 1 unresolved discussion (waiting on @JeffreyAshtonNRCan)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83#-:-NnjvjIJ1oyeGZU1Nva4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @JeffreyAshtonNRCan)

**Review by JeffreyAshtonNRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`schemas/tables/category.csv` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83#-NnjbvcD2xV4yykiR1rb:-NnjwvLd-o55Mf97SpQB:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/e9366474fef14c7ed9c5e2fd341152dd57618b3f/schemas/tables/category.csv#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use same translation here as the table in bucket-content folder... This is why having twice same content can introduce errors hard to debug.
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/83)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JeffreyAshtonNRCan)

**Pull request merged**
