### PR TITLE
Issues #43 and #44

### PR DESCRIPTION
**Pull request by David-Henandez-nrcan**
Code update:
- Clean up of trailing spaces and lines
- Respect the 80 characters/line limit
- More structured code
- A few more improvements.

Regular url separators:
- Changed 'spaces' for 'add sign' in parameter before REST call

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/46)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/46)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @David-Henandez-nrcan)

___
*[`cloud-formation/python/geolocator-lambda.py` line 132 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/46#-NMjrA5iCsPAddTBXuoq:-NMjrA5j9YWQRn5vmt6E:beqoby2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/3558a89b8d69b00dde0b001a5460107f11925572/cloud-formation/python/geolocator-lambda.py#L132)):*
> ```Python
>     # 0. Read and Validate the parameters
>     params_full_list = validate_querystring_against_schema(event,in_api_schema)
> <<<<<<< HEAD
> ```

You have a bad rebase this artefact of a conflict
___
*[`cloud-formation/python/model_manager.py` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/46#-NMjrbwD90AaqELYtjor:-NMjrbwD90AaqELYtjos:b-l6su86) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cc0422af17eaa2de7eec482380aeb78488cca17f/cloud-formation/python/model_manager.py#L3)):*
> ```Python
> import boto3
> 
> def get_s3_bucket():
> ```

Where did you moved all the s3 reading logic?
___
*[`cloud-formation/python/model_manager.py` line 46 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/46#-NMjrVGP-E8jJL6-OaA0:-NMjrVGP-E8jJL6-OaA1:b7zf2ir) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/3558a89b8d69b00dde0b001a5460107f11925572/cloud-formation/python/model_manager.py#L46)):*
> ```Python
>             else:
>                 # Match the data list against the type of list in
>                 for i in range(len(value)):                
> ```

Trailing white spaces

**Review by David-Henandez-nrcan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/46)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`cloud-formation/python/geolocator-lambda.py` line 132 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/46#-NMjrA5iCsPAddTBXuoq:-NN3CjL8-Wo7o1t7Cjmt:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/3558a89b8d69b00dde0b001a5460107f11925572/cloud-formation/python/geolocator-lambda.py#L132)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You have a bad rebase this artefact of a conflict
</blockquote></details>

Done.

**Review by David-Henandez-nrcan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/46)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`cloud-formation/python/model_manager.py` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/46#-NMjrbwD90AaqELYtjor:-NN3ETXu-wMsi7vomT-w:b72dans) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/cc0422af17eaa2de7eec482380aeb78488cca17f/cloud-formation/python/model_manager.py#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Where did you moved all the s3 reading logic?
</blockquote></details>

I moved the logic inside s3_manager python file

**Review by David-Henandez-nrcan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/46)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`cloud-formation/python/model_manager.py` line 46 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/46#-NMjrVGP-E8jJL6-OaA0:-NN3EjrN4_GvlCu0aEWM:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/3558a89b8d69b00dde0b001a5460107f11925572/cloud-formation/python/model_manager.py#L46)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @David-Henandez-nrcan)

**Pull request merged**
