### PR TITLE
Add .csv tables and code to replace consummng json from url

### PR DESCRIPTION
**Pull request by David-Henandez-nrcan**
* Extract once the contents of **geonames** _url code tables_ in **json** format
* for each json files, discard al the unnecessary information and create a table with the code and values for both languages
* transform those tables to **csv** format and add them into the application.
* Modify the code in order to access and make available on demand those tables instead of the _url code tables_  
* Execute Performance Tests
* deploy application

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/66)

### CODE REVIEW

**Comment by David-Henandez-nrcan** [comment]
Additionally.

-  Instead of csv files, the tables might be saved in .**json** format already structured to be read in memory as dictionaries.

- Instead of having this header _['code', 'en, 'fr']_ for each lookup table (province and generic) in the schema. There might have 2 set of tables for each field _{'code', 'value'}_. One for English and other for French in a forked structure inside AWS s3. 

tables/en/province-table.json
tables/en/generic-table.json
tables/fr/province-table.json
tables/fr/generic-table.json

each containing as follow:
_{1: "cité", 
 2:  "ville",
 3:  "village",
...
...
}_
Only the branch for the selected language be passed to the table function, saving complexity to the code.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/66)* status: all files reviewed, 3 unresolved discussions (waiting on @David-Henandez-nrcan)

___
*[`cloud-formation/python/geolocator.py` line 35 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/66#-NRsGlyX1RC04rHRSezk:-NRsGlyX1RC04rHRSezl:by3qfas) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0affdad1d9ee09c59efa4d4128f6930bf587d929/cloud-formation/python/geolocator.py#L35)):*
> ```Python
>             try:
>                 cls.read_schemas(cls)
>                 cls.read_tables(cls)
> ```

Quick question, it is easier to work with CSV instead of JSON? Is it faster in CSV?
___
*[`cloud-formation/python/geolocator.py` line 73 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/66#-NRsGw8J-Efc__mqYC7O:-NRsGw8J-Efc__mqYC7P:beslwjd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0affdad1d9ee09c59efa4d4128f6930bf587d929/cloud-formation/python/geolocator.py#L73)):*
> ```Python
>         self._tables = s3_manager.get_tables(bucket, TABLES_PATH)
>         for table in self._tables:
>             print(f"table: {table}")
> ```

Is this for debugging?
___
*[`cloud-formation/python/s3_manager.py` line 65 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/66#-NRsH9TY9kWtmtoRqIEX:-NRsH9TY9kWtmtoRqIEY:brr4dm8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0affdad1d9ee09c59efa4d4128f6930bf587d929/cloud-formation/python/s3_manager.py#L65)):*
> ```Python
>             for eachRecord in records:
>                 descr = {}
>                 
> ```

Trailing white space

**Review by David-Henandez-nrcan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/66)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`cloud-formation/python/geolocator.py` line 35 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/66#-NRsGlyX1RC04rHRSezk:-NRsMbd28f8TMdDPL1F-:bdn0lbj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0affdad1d9ee09c59efa4d4128f6930bf587d929/cloud-formation/python/geolocator.py#L35)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Quick question, it is easier to work with CSV instead of JSON? Is it faster in CSV?
</blockquote></details>

I think that it will be easier and faster to read and transform into useful data .json files than .csv files.
___
*[`cloud-formation/python/geolocator.py` line 73 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/66#-NRsGw8J-Efc__mqYC7O:-NRsNnhGAZs--AO_pjJt:bcp2sve) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0affdad1d9ee09c59efa4d4128f6930bf587d929/cloud-formation/python/geolocator.py#L73)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this for debugging?
</blockquote></details>

Yes. I will remove it.
___
*[`cloud-formation/python/s3_manager.py` line 65 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/66#-NRsH9TY9kWtmtoRqIEX:-NRsSx3u8ZmkEwf4xX-F:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0affdad1d9ee09c59efa4d4128f6930bf587d929/cloud-formation/python/s3_manager.py#L65)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white space
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/66)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @David-Henandez-nrcan)

**Pull request merged**
