### PR TITLE
55 UI

### PR DESCRIPTION
**Pull request by David-Henandez-nrcan**
Even though the UI has little modifications. 
The latest improvements to the application are included in this pull request

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60)* status: 1 of 11 files reviewed, 15 unresolved discussions (waiting on @David-Henandez-nrcan)

___
*[`README.md` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRD_DSC4LoI6_XANTgD:-NRD_DSD11KE8x4T0DEf:bzhz5t3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/README.md#L5)):*
> ```Markdown
> The Canadian Geospatial Platform (CGP) needs the ability to do Geocoding
> 
> >Geocoding is the process of converting addresses (like "1600 Amphitheatre Parkway, Mountain View, CA") into geographic coordinates (like latitude 37.423021 and longitude -122.083739), which you can use to place markers on a map, or position the map. Google Maps Geocoding A
> ```

Why removing API?
___
*[`cloud-formation/README.md` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRD_QSK4c0TUUB-I-yZ:-NRD_QSK4c0TUUB-I-y_:byjba96) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/cloud-formation/README.md#L5)):*
> ```Markdown
> Geolocator Wrapper API
> The Canadian Geospatial Platform (CGP) needs the ability to do Geocoding
> Geocoding is the process of converting addresses (like "1600 Amphitheatre Parkway, Mountain View, CA") into geographic coordinates (like latitude 37.423021 and longitude -122.083739), which you can use to place markers on a map, or position the map. Google Maps Geocoding API
> ```

Duplicate of other Readme above
___
*[`cloud-formation/README.md` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRD_V0w1rcM1HDpNhw_:-NRD_V0w1rcM1HDpNhwa:b7zf2ir) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/cloud-formation/README.md#L14)):*
> ```Markdown
> 	• Build valid url and parameters for consuming data on each specific geo-service
> 
> 	• Extract the required information from the query and build standard response from it   
> ```

Trailing white spaces
___
*[`cloud-formation/README.md` line 39 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRD_fHvCAqp41zs920b:-NRD_fHvCAqp41zs920c:b-vzrc6n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/cloud-formation/README.md#L39)):*
> ```Markdown
> 
> 	Development, share and deploy
> Visual Studio Code, git, npm 
> ```

Remove trailing white spaces
___
*[`schemas/README.md` line 61 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDafW61C50_P9VXrrq:-NRDafW61C50_P9VXrrr:b-3vkonc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L61)):*
> ```Markdown
>                     "field":"geometry.location.lat",
>                     "lookup": ""
> 				}
> ```

Look everywhere for tab sign and replace by spaces
___
*[`schemas/README.md` line 102 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDarA1Dx3Q9dnpcu_S:-NRDarA1Dx3Q9dnpcu_T:b-vzrc6n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L102)):*
> ```Markdown
>               a list of dictionaries where one matches an specific key-value.
>     * url. The data value comes from and table obtained from a url
>            (deprecated). 
> ```

Remove trailing white spaces
___
*[`schemas/README.md` line 110 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDavC95qU-cKsiEJ4u:-NRDavC95qU-cKsiEJ4v:b-7wm6e6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L110)):*
> ```Markdown
>     Several services at once will ad up to the final delay. 
>   - The size of the load. More items required more time to process. 
>     The more specific the query, the faster the answer will arrive. (it was 
> ```

Remove trailing white space
___
*[`schemas/README.md` line 112 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDayJODF5i3MInXy_e:-NRDayJODF5i3MInXy_f:b-7wm6e6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L112)):*
> ```Markdown
>     The more specific the query, the faster the answer will arrive. (it was 
>     already improved by keeping a list of micro-schemas asociated to each field.
>     Even though the list must be cleared and rebuild for each service, the 
> ```

Remove trailing white space
___
*[`schemas/README.md` line 124 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDb1KJ1kGCkoMErh5M:-NRDb1KJ1kGCkoMErh5N:b-7wm6e6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L124)):*
> ```Markdown
> ### Google API's
>         """
>         To test Google services such as 'findplace' and 'geocode' without the key. 
> ```

Remove trailing white space
___
*[`schemas/README.md` line 125 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDb23y3onSvu5pF7sI:-NRDb23y3onSvu5pF7sJ:b-7wm6e6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L125)):*
> ```Markdown
>         """
>         To test Google services such as 'findplace' and 'geocode' without the key. 
>         Simulate the return from the service by bypassing the url_request with a 
> ```

Remove trailing white space
___
*[`schemas/README.md` line 140 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDb6xwAB09iZICe0yQ:-NRDb6xwAB09iZICe0yR:b-7wm6e6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L140)):*
> ```Markdown
>                 },
>             }
>         * geolocator_lambda.py must be 'temporarily' modified in this way:        
> ```

Remove trailing white space
___
*[`schemas/api/in-api-schema.json` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDbAFZ9NohFs_1xQxW:-NRDbAF_6LXE4C_BRosb:b-2weaoj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/api/in-api-schema.json#L37)):*
> ```JSON
>             }
>           },
>           "required": [{"q"}],
> ```

Why object instead of array?
___
*[`schemas/services/findplace-schema.json` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDbGyW6mvskwFpGPsG:-NRDbGyW6mvskwFpGPsH:b-7wm6e6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/services/findplace-schema.json#L3)):*
> ```JSON
> {
>   "url" : "https://maps.googleapis.com/maps/api/place/findplacefromtext/json",
>   
> ```

Remove trailing white space
___
*[`schemas/services/geocode-schema.json` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDbLuV3fJu5auk8_kk:-NRDbLuV3fJu5auk8_kl:b-7wm6e6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/services/geocode-schema.json#L3)):*
> ```JSON
> {
>   "url" : "https://maps.googleapis.com/maps/api/geocode/json",
>   
> ```

Remove trailing white space
___
*[`schemas/services/nominatim-schema.json` line 31 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDbY1dCmllgLv9ca3R:-NRDbY1eC_ZGwG8iKpHw:bcux9jt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/services/nominatim-schema.json#L31)):*
> ```JSON
>                 "lookup": ""
>             },
>             "bbox": [
> ```

Why array? Should be only one bbox by item?

**Review by David-Henandez-nrcan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60)* status: 1 of 11 files reviewed, 15 unresolved discussions (waiting on @jolevesq)

___
*[`README.md` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRD_DSC4LoI6_XANTgD:-NRE4MIgALfiW6V5pm7b:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/README.md#L5)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why removing API?
</blockquote></details>

Done.
___
*[`cloud-formation/README.md` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRD_QSK4c0TUUB-I-yZ:-NRE9o9Y7ICGaBAZxpbK:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/cloud-formation/README.md#L5)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Duplicate of other Readme above
</blockquote></details>

Done.
___
*[`cloud-formation/README.md` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRD_V0w1rcM1HDpNhw_:-NREAYff8ZbItyMeZwqq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/cloud-formation/README.md#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Done.
___
*[`cloud-formation/README.md` line 39 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRD_fHvCAqp41zs920b:-NREAbO84ofbWp39db8g:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/cloud-formation/README.md#L39)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white spaces
</blockquote></details>

Done.
___
*[`schemas/README.md` line 61 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDafW61C50_P9VXrrq:-NREIVHE1zn_8Jc2J_dJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Look everywhere for tab sign and replace by spaces
</blockquote></details>

Done.
___
*[`schemas/README.md` line 102 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDarA1Dx3Q9dnpcu_S:-NREIYlG5jSP-Yv4rs3n:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L102)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white spaces
</blockquote></details>

Done.
___
*[`schemas/README.md` line 110 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDavC95qU-cKsiEJ4u:-NREI_wQ6G1tIoBfmZ5d:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L110)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[`schemas/README.md` line 112 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDayJODF5i3MInXy_e:-NREIiiHBMPiySe6R8Ds:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L112)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[`schemas/README.md` line 124 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDb1KJ1kGCkoMErh5M:-NREIn2N-Hx5gbPd6NQ8:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L124)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[`schemas/README.md` line 125 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDb23y3onSvu5pF7sI:-NREIsv72m9bljNFXH3K:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L125)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[`schemas/README.md` line 140 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDb6xwAB09iZICe0yQ:-NREIy7N2f6kb47fpNji:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/README.md#L140)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[`schemas/api/in-api-schema.json` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDbAFZ9NohFs_1xQxW:-NREMBZRBOupBDy_p-np:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/api/in-api-schema.json#L37)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why object instead of array?
</blockquote></details>

Done.
___
*[`schemas/services/findplace-schema.json` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDbGyW6mvskwFpGPsG:-NREMkaCEFK8vAT0--zq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/services/findplace-schema.json#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[`schemas/services/geocode-schema.json` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDbLuV3fJu5auk8_kk:-NRENP5m2l-21vjlvT9z:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/services/geocode-schema.json#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[`schemas/services/nominatim-schema.json` line 31 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60#-NRDbY1dCmllgLv9ca3R:-NRENZdG6c4-rQoM23VW:bx8ury1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/0382300d064f085498915187c4bb3041c6556b43/schemas/services/nominatim-schema.json#L31)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why array? Should be only one bbox by item?
</blockquote></details>

in this particular case, instead of copying the whole set of values to the bbox field, each coordinate must be reassigned to its standard position in the array.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 3 of 11 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @David-Henandez-nrcan)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/60)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @David-Henandez-nrcan)

**Pull request merged**
