### PR TITLE
add function 'average' to calculate lat,lng from bounding box

### PR DESCRIPTION
**Pull request by David-Henandez-nrcan**
* Modification of nts-schema adding lookup 'average' to fields 'lat', 'lng'.
* Modify model manager to match schema and add get_average() function
* tested on nts returns

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/62)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/62)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @David-Henandez-nrcan)

___
*[`README.md` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/62#-NRJTdPJB242zGQ0uGU9:-NRJTdPJB242zGQ0uGUA:bz9vife) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/21919639a7de725d52eb7894b50221fb49f9ee82/README.md#L15)):*
> ```Markdown
> Sample call to the API:
> ```
> https://fr59c5usw4.execute-api.ca-central-1.amazonaws.com/dev?q=Meech%20lake&lang=en&keys=geonames,nominatim
> ```

HTML parsing %20 should not be part of url sample, it is added when query is created.
___
*[`schemas/README.md` line 112 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/62#-NRJUEbr4ys34xuMCQpM:-NRJUEbr4ys34xuMCQpN:bbt7ejs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/21919639a7de725d52eb7894b50221fb49f9ee82/schemas/README.md#L112)):*
> ```Markdown
>               a list of dictionaries where one must match an specific key/value tuple
> 	* average. Calculate the average of a subset of numeric values from a field
>                containing a list of numerics (such as bbox)	
> ```

Remove trailing tab
___
*[`schemas/services/nts-schema.json` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/62#-NRJUNjR7dVsXmG2ze9y:-NRJUNjR7dVsXmG2ze9z:bfqrg2z) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/21919639a7de725d52eb7894b50221fb49f9ee82/schemas/services/nts-schema.json#L23)):*
> ```JSON
>                 },
>                 "lat": {
>                     "field": "bbox",
> ```

Humm, I would not manage this from the schema. Only from code.... if there is no correspondence for lat/lng, before returning que query, just extract lat/lng value. Would it be simplier? We do not need to deal with this at att, it is just a check at the end.

**Review by David-Henandez-nrcan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/62)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`README.md` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/62#-NRJTdPJB242zGQ0uGU9:-NRJXqtO-d7cQuxl2jVh:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/21919639a7de725d52eb7894b50221fb49f9ee82/README.md#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

HTML parsing %20 should not be part of url sample, it is added when query is created.
</blockquote></details>

Done.
___
*[`schemas/README.md` line 112 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/62#-NRJUEbr4ys34xuMCQpM:-NRJY2p82fcnCQgf1p_q:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/21919639a7de725d52eb7894b50221fb49f9ee82/schemas/README.md#L112)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing tab
</blockquote></details>

Done.
___
*[`schemas/services/nts-schema.json` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/62#-NRJUNjR7dVsXmG2ze9y:-NRJxkwH4lZVh93mWNJ3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/21919639a7de725d52eb7894b50221fb49f9ee82/schemas/services/nts-schema.json#L23)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Humm, I would not manage this from the schema. Only from code.... if there is no correspondence for lat/lng, before returning que query, just extract lat/lng value. Would it be simplier? We do not need to deal with this at att, it is just a check at the end. 
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/62)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @David-Henandez-nrcan)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/62)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @David-Henandez-nrcan)

**Pull request merged**
