### PR TITLE
Create performance tests

### PR DESCRIPTION
**Pull request by David-Henandez-nrcan**
- Create parameters test for several scenarios
- Create performance test for variable number of calls (first and only parameter)
- Refactoring:
  - geolocator_lambda.py
  - geolocator.py
  - model_manager.py
  - s3_manager.py
- Adding:
  - constants.py
  - url_methods.py

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49)* status: all files reviewed, 4 unresolved discussions (waiting on @David-Henandez-nrcan)

___
*[`cloud-formation/python/geolocator-lambda.py` line 10 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49#-NNfvwCW2ZwF11JtQ16D:-NNfvwCW2ZwF11JtQ16E:b-6vmm6y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/3729dfa23599bf435edffda384a623bf8d80943c/cloud-formation/python/geolocator-lambda.py#L10)):*
> ```Python
>     Main function. When called, performs specific actions in order to
>           extract, adapt, and return REST data from several specific services.
>     
> ```

Trailling white space
___
*[`cloud-formation/python/geolocator-lambda.py` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49#-NNfw0y92-yKAr2MlHmx:-NNfw0y92-yKAr2MlHmy:b-6vmm6y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/3729dfa23599bf435edffda384a623bf8d80943c/cloud-formation/python/geolocator-lambda.py#L19)):*
> ```Python
>     - Validation. The resulting data is validated against an output schema to
>                   be 'conformed' before be handed to the front-end
>     
> ```

Trailling white space
___
*[`cloud-formation/python/model_manager.py` line 135 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49#-NNfwGK-D5TOMtrZjRIN:-NNfwGK-D5TOMtrZjRIO:b-6vmm6y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/3729dfa23599bf435edffda384a623bf8d80943c/cloud-formation/python/model_manager.py#L135)):*
> ```Python
>         else:
>             print("Dont know!")
>             
> ```

Trailling white space
___
*[`cloud-formation/python/url_methods.py` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49#-NNfwZY1Cc25SAQe3nYA:-NNfwZY1Cc25SAQe3nYB:b-6vmm6y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/3729dfa23599bf435edffda384a623bf8d80943c/cloud-formation/python/url_methods.py#L79)):*
> ```Python
>       model: the model with the rules to assemble the url and parameters
>       params: The list of parameters to be used to build the url
>       
> ```

Trailling white space



_Code quote:_
```Python
·
```

**Review by David-Henandez-nrcan — COMMENTED** [review]
- Correction of trailing white spaces
- Rename repertory from 'geo-services' to 'services'
- Modify index.html to test calling AWS API

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49#-:-NNgUOBo-eWtTOR7glqH:b-t4yl8d)* status: all files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[`cloud-formation/python/geolocator-lambda.py` line 10 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49#-NNfvwCW2ZwF11JtQ16D:-NNgPv056tvt76uhWP7k:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/3729dfa23599bf435edffda384a623bf8d80943c/cloud-formation/python/geolocator-lambda.py#L10)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailling white space
</blockquote></details>

Done.
___
*[`cloud-formation/python/geolocator-lambda.py` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49#-NNfw0y92-yKAr2MlHmx:-NNgPvni882jLu2tNIiv:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/3729dfa23599bf435edffda384a623bf8d80943c/cloud-formation/python/geolocator-lambda.py#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailling white space
</blockquote></details>

Done.
___
*[`cloud-formation/python/model_manager.py` line 135 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49#-NNfwGK-D5TOMtrZjRIN:-NNgQBI71fZZNllnZJtn:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/3729dfa23599bf435edffda384a623bf8d80943c/cloud-formation/python/model_manager.py#L135)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailling white space
</blockquote></details>

Done.
___
*[`cloud-formation/python/url_methods.py` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49#-NNfwZY1Cc25SAQe3nYA:-NNgTFzC24KNDC6XhCfo:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/blob/3729dfa23599bf435edffda384a623bf8d80943c/cloud-formation/python/url_methods.py#L79)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailling white space
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @David-Henandez-nrcan)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview-api-geolocator/49)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @David-Henandez-nrcan)

**Pull request merged**
